version: '3.5'
services:
  protocol:
    image: protocol
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /home/whatsername/course-networks/hw1:/app

volumes:
  app: